server:
  port: 80

spring:
  application:
    name: security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.146.239:3306/study?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    # 注明所使用的数据库
    platform: mysql
    # 数据源(数据池)
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置初始化大小、最小、最大
      initial-size: 5
      min-idle: 10
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 2000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
        enabled: true
      # 缓存游标
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      # 如果有initialSize数量较多时，打开会加快应用启动时间
      async-init: true
      # 慢查询
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
  redis:
    host: 172.18.146.239
    port: 6379
    password: root
    database: 0
  security:
    user:
      name: admin
      password: admin

mybatis-plus:
  global-config:
    banner: false

